<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Derek Davis";
$wgMetaNamespace = "Derek_Davis";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = getenv('MW_SCRIPT_PATH') ?: "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv('MW_SERVER') ?: "http://localhost:8082";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "sqlite";
$wgDBserver = "";
$wgDBname = "my_wiki";
$wgDBuser = "";
$wgDBpassword = "";

# SQLite-specific settings
$wgSQLiteDataDir = "/var/www/data";
$wgObjectCaches[CACHE_DB] = [
	'class' => SqlBagOStuff::class,
	'loggroup' => 'SQLBagOStuff',
	'server' => [
		'type' => 'sqlite',
		'dbname' => 'wikicache',
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0
	]
];
$wgLocalisationCacheConf['storeServer'] = [
	'type' => 'sqlite',
	'dbname' => "{$wgDBname}_l10n_cache",
	'tablePrefix' => '',
	'variables' => [ 'synchronous' => 'NORMAL' ],
	'dbDirectory' => $wgSQLiteDataDir,
	'trxMode' => 'IMMEDIATE',
	'flags' => 0
];
$wgJobTypeConf['default'] = [
	'class' => 'JobQueueDB',
	'claimTTL' => 3600,
	'server' => [
		'type' => 'sqlite',
		'dbname' => "{$wgDBname}_jobqueue",
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0
	]
];
$wgResourceLoaderUseObjectCacheForDeps = true;

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "dd9fffe67b7b02f3e09820d0d6b8fc0e7b491ffbc5bb85264e9839be34752f7d";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "0f6447ead142336e";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: Vector 2022 (modern, matches OpenFS enterprise theme)
$wgDefaultSkin = "vector-2022";

# Enabled skins.
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# ── Vector 2022: pin sidebar open by default ──────────────────────────────────
$wgVectorDefaultSidebarVisibleForAuthorisedUser = true;
$wgVectorDefaultSidebarVisibleForAnon = true;
$wgDefaultUserOptions['vector-sidebarvisible'] = 1;

# ── Site identity ─────────────────────────────────────────────────────────────
$wgSitename = "Derek Davis";
$wgMetaNamespace = "Derek_Davis";
$wgLogos = [
    '1x'   => "$wgScriptPath/openfs-icon.svg",
    'icon' => "$wgScriptPath/openfs-icon.svg",
    'wordmark' => [
        'src'    => "$wgScriptPath/openfs-wordmark.svg",
        'width'  => 160,
        'height' => 28,
    ],
];

# ── OpenFS Theme CSS ──────────────────────────────────────────────────────────
$wgHooks['BeforePageDisplay'][] = function ( $out, $skin ) {
    $out->addInlineStyle( '
        /* ── OpenFS Enterprise Theme — Vector 2022 / MW 1.43 ── */

        /* Header */
        .vector-header,
        .vector-header-start,
        .vector-header-end,
        .mw-logo {
            background-color: #0f172a !important;
            border-bottom-color: #334155 !important;
        }
        .vector-header a,
        .vector-header button,
        #p-personal a,
        .vector-user-links a,
        .vector-user-menu a {
            color: #f1f5f9 !important;
        }

        /* Search */
        .vector-search-box .cdx-text-input__input,
        #searchInput {
            background-color: #1e293b !important;
            border-color: #334155 !important;
            color: #f1f5f9 !important;
        }
        .vector-search-box .cdx-text-input__input::placeholder { color: #64748b !important; }

        /* ── Sidebar: every container Vector 2022 might use ── */
        .vector-column-start,
        .vector-main-menu-container,
        #vector-main-menu-pinned-container,
        #vector-main-menu,
        .vector-main-menu,
        #mw-panel,
        .mw-panel {
            background-color: #0f172a !important;
        }

        /* Sidebar portlet wrappers */
        html body .vector-column-start .mw-portlet,
        html body .vector-column-start .vector-menu-portal,
        html body #vector-main-menu .mw-portlet,
        html body #vector-main-menu .vector-menu-portal,
        html body #mw-panel .mw-portlet {
            background-color: #0f172a !important;
        }

        /* Section headings (ARTIFACTS, BOOKS, etc.) */
        html body .vector-column-start h3,
        html body .vector-column-start .mw-portlet-heading,
        html body .vector-column-start .mw-portlet-heading button,
        html body #vector-main-menu h3,
        html body #vector-main-menu .mw-portlet-heading button,
        html body #mw-panel h3 {
            color: #94a3b8 !important;
            background-color: transparent !important;
            font-size: 0.68rem !important;
            font-weight: 700 !important;
            letter-spacing: 0.1em !important;
            text-transform: uppercase !important;
            border-bottom: 1px solid #334155 !important;
            padding-bottom: 4px !important;
        }

        /* Nav links — needs html body prefix to beat skin specificity */
        html body .vector-column-start a,
        html body .vector-column-start li a,
        html body #vector-main-menu a,
        html body #vector-main-menu li a,
        html body #mw-panel a,
        html body .vector-menu-portal a,
        html body .mw-portlet-navigation a {
            color: #cbd5e1 !important;
            font-size: 0.875rem !important;
        }
        html body .vector-column-start a:hover,
        html body #vector-main-menu a:hover,
        html body .vector-menu-portal a:hover {
            color: #a5b4fc !important;
            text-decoration: none !important;
        }

        /* ── Content area ── */
        #mw-content-text a { color: #4f46e5 !important; }
        #mw-content-text a:hover { color: #6366f1 !important; }

        /* Tabs */
        .vector-tab-noicon.selected > a {
            color: #6366f1 !important;
            border-bottom: 2px solid #6366f1 !important;
        }

        /* Footer */
        .mw-footer {
            background-color: #0f172a !important;
            border-top: 1px solid #334155 !important;
            color: #64748b !important;
        }
        .mw-footer a { color: #64748b !important; }

        /* Page title */
        .mw-page-title-main {
            color: var(--openfs-navy) !important;
        }

        /* Sidebar toggle button */
        .mw-checkbox-hack-button {
            color: var(--openfs-text) !important;
        }

        /* Footer */
        .mw-footer {
            border-top: 1px solid var(--openfs-border) !important;
            background: var(--openfs-navy) !important;
            color: var(--openfs-muted) !important;
        }
        .mw-footer a { color: var(--openfs-muted) !important; }
    ' );
};


# ── Uploads ───────────────────────────────────────────────────────────────────
$wgEnableUploads = true;
$wgUploadPath = "$wgScriptPath/images";

# ── Bot / API access ──────────────────────────────────────────────────────────
# Allow the OpenFS agent bot to edit via the API
$wgGroupPermissions['bot']['apihighlimits'] = true;

# ── Short URLs ────────────────────────────────────────────────────────────────
$wgArticlePath = "$wgScriptPath/wiki/$1";

# ── OpenFS terminal embed ─────────────────────────────────────────────────────
$wgRawHtml = true;

# ── Gadgets extension ─────────────────────────────────────────────────────────
wfLoadExtension( 'Gadgets' );

# ── Debugging (Railway) ───────────────────────────────────────────────────────
$wgShowExceptionDetails = true;

# ── SQLite data dir (allow env override) ─────────────────────────────────────
if ( getenv('MW_SQLITE_DATA_DIR') ) {
    $wgSQLiteDataDir = getenv('MW_SQLITE_DATA_DIR');
}

# ── Bot / migration rate limits ───────────────────────────────────────────────
# Allow bots to edit freely (needed for bulk migration from local wiki)
$wgRateLimits['edit']['user']    = [ 1000, 60 ]; // 1000 edits per minute
$wgRateLimits['edit']['newbie']  = [ 1000, 60 ];
$wgRateLimits['edit']['ip']      = [ 1000, 60 ];

# End of automatically generated settings.

