<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Derek Davis";
$wgMetaNamespace = "Derek_Davis";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = getenv('MW_SCRIPT_PATH') ?: "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv('MW_SERVER') ?: "http://localhost:8082";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "sqlite";
$wgDBserver = "";
$wgDBname = "my_wiki";
$wgDBuser = "";
$wgDBpassword = "";

# SQLite-specific settings
$wgSQLiteDataDir = "/var/www/data";
$wgObjectCaches[CACHE_DB] = [
	'class' => SqlBagOStuff::class,
	'loggroup' => 'SQLBagOStuff',
	'server' => [
		'type' => 'sqlite',
		'dbname' => 'wikicache',
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0
	]
];
$wgLocalisationCacheConf['storeServer'] = [
	'type' => 'sqlite',
	'dbname' => "{$wgDBname}_l10n_cache",
	'tablePrefix' => '',
	'variables' => [ 'synchronous' => 'NORMAL' ],
	'dbDirectory' => $wgSQLiteDataDir,
	'trxMode' => 'IMMEDIATE',
	'flags' => 0
];
$wgJobTypeConf['default'] = [
	'class' => 'JobQueueDB',
	'claimTTL' => 3600,
	'server' => [
		'type' => 'sqlite',
		'dbname' => "{$wgDBname}_jobqueue",
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0
	]
];
$wgResourceLoaderUseObjectCacheForDeps = true;

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "dd9fffe67b7b02f3e09820d0d6b8fc0e7b491ffbc5bb85264e9839be34752f7d";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "0f6447ead142336e";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: Vector 2022 (modern, matches OpenFS enterprise theme)
$wgDefaultSkin = "vector-2022";

# Enabled skins.
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# ── Site identity ─────────────────────────────────────────────────────────────
$wgSitename = "Derek Davis";
$wgMetaNamespace = "Derek_Davis";
$wgLogos = [
    '1x'   => "$wgScriptPath/openfs-icon.svg",
    'icon' => "$wgScriptPath/openfs-icon.svg",
    'wordmark' => [
        'src'    => "$wgScriptPath/openfs-wordmark.svg",
        'width'  => 160,
        'height' => 28,
    ],
];

# ── OpenFS Theme CSS ──────────────────────────────────────────────────────────
$wgHooks['BeforePageDisplay'][] = function ( $out, $skin ) {
    $out->addInlineStyle( '
        /* ── OpenFS Enterprise Theme ── */
        :root {
            --openfs-navy:       #0f172a;
            --openfs-navy-mid:   #1e293b;
            --openfs-navy-light: #334155;
            --openfs-accent:     #6366f1;
            --openfs-accent-dim: #4f46e5;
            --openfs-text:       #f1f5f9;
            --openfs-muted:      #94a3b8;
            --openfs-border:     #334155;
        }

        /* Sidebar */
        .mw-sidebar,
        .vector-sidebar,
        #mw-sidebar-checkbox ~ .mw-sidebar,
        .mw-table-of-contents-container,
        .vector-sidebar-container,
        .vector-sidebar-container-no-toc {
            background: var(--openfs-navy) !important;
            border-color: var(--openfs-border) !important;
        }

        /* Sidebar portal headings */
        .vector-menu-portal > .vector-menu-heading,
        .mw-portlet > h3,
        .mw-portlet-label {
            color: var(--openfs-muted) !important;
            font-size: 0.7rem !important;
            font-weight: 600 !important;
            letter-spacing: 0.08em !important;
            text-transform: uppercase !important;
            border-bottom: 1px solid var(--openfs-border) !important;
            padding-bottom: 4px !important;
        }

        /* Sidebar nav links */
        .vector-menu-portal .vector-menu-content a,
        .mw-portlet .mw-portlet-body a,
        #p-navigation a, #p-tb a, #p-cactions a {
            color: var(--openfs-text) !important;
            font-size: 0.875rem !important;
        }
        .vector-menu-portal .vector-menu-content a:hover,
        .mw-portlet .mw-portlet-body a:hover {
            color: #a5b4fc !important;
            text-decoration: none !important;
        }

        /* Logo area background */
        .mw-logo, .vector-header-start {
            background: var(--openfs-navy) !important;
        }

        /* Top header */
        .vector-header,
        #vector-page-titlebar,
        .mw-header {
            background: var(--openfs-navy) !important;
            border-bottom: 1px solid var(--openfs-border) !important;
        }

        /* Header links (user menu, etc.) */
        .vector-user-menu .vector-menu-content a,
        #p-personal a,
        .vector-header a {
            color: var(--openfs-text) !important;
        }

        /* Search bar */
        .vector-search-box input[type="search"],
        #searchInput {
            background: var(--openfs-navy-mid) !important;
            border-color: var(--openfs-border) !important;
            color: var(--openfs-text) !important;
            border-radius: 6px !important;
        }
        .vector-search-box input[type="search"]::placeholder {
            color: var(--openfs-muted) !important;
        }

        /* Tabs (edit, view, history) */
        .vector-page-toolbar,
        .mw-portlet-views {
            border-bottom: 1px solid #e2e8f0 !important;
        }
        .vector-tab-noicon.selected a,
        .selected a {
            color: var(--openfs-accent) !important;
            border-bottom: 2px solid var(--openfs-accent) !important;
        }

        /* Accent on links in content */
        #mw-content-text a {
            color: var(--openfs-accent-dim) !important;
        }
        #mw-content-text a:hover {
            color: var(--openfs-accent) !important;
        }

        /* Page title */
        .mw-page-title-main {
            color: var(--openfs-navy) !important;
        }

        /* Sidebar toggle button */
        .mw-checkbox-hack-button {
            color: var(--openfs-text) !important;
        }

        /* Footer */
        .mw-footer {
            border-top: 1px solid var(--openfs-border) !important;
            background: var(--openfs-navy) !important;
            color: var(--openfs-muted) !important;
        }
        .mw-footer a { color: var(--openfs-muted) !important; }
    ' );
};


# ── Uploads ───────────────────────────────────────────────────────────────────
$wgEnableUploads = true;
$wgUploadPath = "$wgScriptPath/images";

# ── Bot / API access ──────────────────────────────────────────────────────────
# Allow the OpenFS agent bot to edit via the API
$wgGroupPermissions['bot']['apihighlimits'] = true;

# ── Short URLs ────────────────────────────────────────────────────────────────
$wgArticlePath = "$wgScriptPath/wiki/$1";

# ── OpenFS terminal embed ─────────────────────────────────────────────────────
$wgRawHtml = true;

# ── Gadgets extension ─────────────────────────────────────────────────────────
wfLoadExtension( 'Gadgets' );

# ── Debugging (Railway) ───────────────────────────────────────────────────────
$wgShowExceptionDetails = true;

# ── SQLite data dir (allow env override) ─────────────────────────────────────
if ( getenv('MW_SQLITE_DATA_DIR') ) {
    $wgSQLiteDataDir = getenv('MW_SQLITE_DATA_DIR');
}

# ── Bot / migration rate limits ───────────────────────────────────────────────
# Allow bots to edit freely (needed for bulk migration from local wiki)
$wgRateLimits['edit']['user']    = [ 1000, 60 ]; // 1000 edits per minute
$wgRateLimits['edit']['newbie']  = [ 1000, 60 ];
$wgRateLimits['edit']['ip']      = [ 1000, 60 ];

# End of automatically generated settings.

